local function readFile(path)
    if type(readfile) == "function" then return assert(readfile(path)) end
    local handle = assert(io.open(path, "rb"))
    local text = handle:read("*a")
    handle:close()
    return text
end

local core = readFile("Decursive/Dcr_CureBindings.lua")
local muf = readFile("Decursive/Dcr_DebuffsFrame.lua")
local native = readFile("Decursive/Dcr_12_1.lua")
local init = readFile("Decursive/DCR_init.lua")
local events = readFile("Decursive/Dcr_Events.lua")
local options = readFile("Decursive_Options/V13/Pages/Cure.lua")
local advanced = readFile("Decursive_Options/Modern/ZD_UI.lua")
local profile = readFile("Decursive/Dcr_ProfileManager.lua")
local ioSource = readFile("Decursive/Dcr_ProfileIO.lua")

local function requireText(source, text, message)
    assert(source:find(text, 1, true), message or ("missing: " .. text))
end

requireText(core, 'SIMPLE_FRIENDLY_GESTURES = {')
requireText(core, 'TARGET_GESTURE = "*%s3"')
requireText(core, 'FOCUS_GESTURE = "ctrl-%s3"')
requireText(core, 'PVP_BANDAGE_GESTURE = "*%s5"')
requireText(core, 'function CureBindings:ScanCarriedPvPBandages(externalItemID)')
requireText(core, 'containerAPI.GetContainerNumSlots')
requireText(core, 'containerAPI.GetContainerItemInfo')
requireText(core, 'itemAPI.GetItemSpell')
requireText(core, 'itemAPI.IsUsableItem')
requireText(core, 'itemAPI.GetDetailedItemLevelInfo')
requireText(core, 'bagEnum.ReagentBag')
requireText(core, 'local selected = external or builtIn')
assert(not core:find('212640', 1, true), "the resolver must use the existing DSI spell identity")
requireText(core, 'action.category = "FRIENDLY_CURE"')
requireText(core, 'action.category = action.areaUtility and "AREA_UTILITY"')
requireText(core, 'return false, "duplicate-gesture"')
requireText(core, 'self.pendingRefresh = reason or true')
requireText(core, 'profile.CureBindingMode = MANUAL_MODE')
requireText(core, 'profile.CureBindingMode = AUTO_MODE')

requireText(muf, 'targetGesture:format("type"), "target"')
requireText(muf, 'focusGesture:format("type"), "focus"')
requireText(muf, 'local binding = macroData.binding')
requireText(muf, 'D:GetCureBindingPriorityForGesture(requestedGesture)')
assert(not muf:find('self:SetUnstableAttribute(mouseButtons[2]:format("macrotext"), fallbackMacro)', 1, true))

requireText(native, 'D:GetCureBindingPriorityForType(debuffType)')
requireText(native, 'D:GetCureBindingPriorityForSpell(spellName)')
requireText(init, 'D:BuildSmartRezMacroText(')
requireText(init, 'binding = binding')
requireText(init, 'areaUtility = true')
requireText(init, 'pvpBandage = true')
requireText(init, 'D.eventFrame:RegisterEvent("ITEM_DATA_LOAD_RESULT")')
requireText(events, 'self:RefreshMUFActionMacros("PLAYER_ENTERING_WORLD")')
requireText(events, '"BAG_UPDATE_DELAYED"')
requireText(events, 'function D:ITEM_DATA_LOAD_RESULT()')
requireText(events, '"GET_ITEM_INFO_RECEIVED"')

requireText(options, '"Simple Two-Button"')
requireText(options, 'local function manualGestureValues()')
requireText(options, 'Controls:Cycle(bindings, "Cure slot " .. slot, manualGestureValues')
requireText(options, 'D:SetManualCureBinding(action.actionKey, value)')
requireText(options, '"Middle: target  ·  Ctrl+Middle: focus"')
requireText(options, '"Button5: no verified PvP bandage available"')
requireText(options, '"CURE_BINDING_BANDAGE_HELP"')
requireText(options, 'bandage.bandageItemLevelPublic')
requireText(advanced, 'Decursive still uses supported secure macro attributes internally')

requireText(profile, 'SCHEMA_VERSION = 4')
requireText(profile, 'migrateVariantBindingPolicy')
requireText(profile, 'profile.CureBindingMode = "MANUAL"')
requireText(ioSource, 'CureBindingMode = { AUTO = true, MANUAL = true }')
requireText(ioSource, 'validateCureBindingManual')

io.stdout:write("OK: secure cure attributes, native color alignment, UI, migration, and profile I/O invariants\n")
